// Practice Studio: local-only sessions and goal plans.
const root=document.getElementById('practice-studio-content');
const KEY='eriks-music-lab:practice-studio:v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
let data={sessions:[],goals:[]},month=new Date();month.setDate(1);
try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.sessions)&&Array.isArray(x.goals))data=x;}catch{}
let message='';
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));message='Saved on this device.';}catch{message='Could not save: check browser storage.';}}
const instruments=['Piano','Voice / Singing','Guitar','Bass','Violin','Drums','Wind instrument','Other'];
function options(items){return items.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');}
function minutes(a){return Math.round(a.reduce((n,s)=>n+(s.status==='done'?Number(s.minutes)||0:0),0));}
function pretty(n){return Math.floor(n/60)+'h '+String(n%60).padStart(2,'0')+'m';}
function render(){
 const now=today(),weekStart=new Date();weekStart.setHours(0,0,0,0);weekStart.setDate(weekStart.getDate()-(weekStart.getDay()+6)%7);
 const wk=[weekStart.getFullYear(),String(weekStart.getMonth()+1).padStart(2,'0'),String(weekStart.getDate()).padStart(2,'0')].join('-');const ym=now.slice(0,7);
 const done=data.sessions.filter(s=>s.status==='done');
 const voiceMinutes=minutes(done.filter(s=>s.instrument==='Voice / Singing'&&s.date>=new Date(Date.now()-4*86400000).toLocaleDateString('sv-SE')));
 const thisWeek=done.filter(s=>s.date>=wk),thisMonth=done.filter(s=>s.date.slice(0,7)===ym);
 const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),offset=(first.getDay()+6)%7;
 let cells='<div class="ps-weekdays">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>'<span>'+x+'</span>').join('')+'</div><div class="ps-calendar">';
 for(let i=0;i<offset;i++)cells+='<span></span>';
 for(let i=1;i<=last.getDate();i++){const day=month.getFullYear()+'-'+String(month.getMonth()+1).padStart(2,'0')+'-'+String(i).padStart(2,'0');const ss=data.sessions.filter(s=>s.date===day);cells+='<button type="button" class="ps-day '+(day===now?'ps-today':'')+'" data-date="'+day+'"><strong>'+i+'</strong><small>'+ss.filter(s=>s.status==='done').length+' ✓ · '+ss.filter(s=>s.status==='planned').length+' ◦</small></button>';}
 cells+='</div>';
 root.innerHTML='<div class="ps-stats"><div><small>This week</small><strong>'+pretty(minutes(thisWeek))+'</strong></div><div><small>This month</small><strong>'+pretty(minutes(thisMonth))+'</strong></div><div><small>All time</small><strong>'+pretty(minutes(done))+'</strong></div></div>'+
 (voiceMinutes>=360?'<div class="ps-panel" role="status"><strong>Voice recovery reminder</strong><p>You have logged '+pretty(voiceMinutes)+' of singing in the last five days. Consider lighter practice and rest, especially if your voice feels tired. There is no universal safe-hour cutoff.</p></div>':'')+'<div class="ps-panel"><div class="ps-heading"><h2>Practice Calendar</h2><div><button type="button" id="ps-prev">←</button> '+first.toLocaleDateString('en-US',{month:'long',year:'numeric'})+' <button type="button" id="ps-next">→</button></div></div>'+cells+'</div>'+
 '<div class="ps-panel"><h2>Add a practice session</h2><form id="ps-session"><div class="ps-fields"><label>Date<input name="date" type="date" value="'+now+'" required></label><label>Instrument<select name="instrument">'+options(instruments)+'</select></label><label>Minutes<input name="minutes" type="number" min="1" max="1440" value="30" required></label><label>Status<select name="status"><option value="done">Completed</option><option value="planned">Planned</option></select></label><label>How was it? (1–5)<select name="rating"><option value="">Not rated</option>'+[1,2,3,4,5].map(i=>'<option value="'+i+'">'+i+'/5</option>').join('')+'</select></label></div><label>Notes<textarea name="notes" rows="2" maxlength="1000" placeholder="What did you practice?"></textarea></label><button class="primary" type="submit">Save session</button></form></div>'+
 '<div class="ps-panel"><h2>Create a practice goal</h2><p class="micro">Generate sessions for your available weekdays. Adjust the plan as you go.</p><form id="ps-goal"><label>Goal<input name="title" required maxlength="100" placeholder="Learn a piano piece"></label><div class="ps-fields"><label>Instrument<select name="instrument">'+options(instruments)+'</select></label><label>Deadline<input name="deadline" type="date" min="'+now+'" required></label><label>Minutes per session<input name="minutes" type="number" min="5" max="240" value="30" required></label></div><fieldset><legend>Available weekdays</legend>'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((x,i)=>'<label class="ps-check"><input type="checkbox" name="day" value="'+i+'" '+([0,2,4].includes(i)?'checked':'')+'>'+x+'</label>').join('')+'</fieldset><button type="submit" class="primary">Generate calendar plan</button></form></div>'+
 '<div class="ps-panel"><h2>Upcoming and recent sessions</h2><div id="ps-entries">'+(data.sessions.length?data.sessions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,60).map(s=>'<div class="ps-entry"><div><strong>'+esc(s.date)+' · '+esc(s.instrument)+'</strong><small>'+s.minutes+' min · '+(s.status==='done'?'Completed':'Planned')+(s.rating?' · '+s.rating+'/5':'')+'</small><p>'+esc(s.notes||'')+'</p></div><div><button type="button" data-toggle="'+esc(s.id)+'">'+(s.status==='planned'?'Mark done':'Plan again')+'</button><button type="button" data-delete="'+esc(s.id)+'" aria-label="Delete session">×</button></div></div>').join(''):'<p class="micro">No sessions yet.</p>')+'</div></div><p class="micro" role="status">'+esc(message)+'</p><p class="micro">Voice practice: listen to fatigue, hoarseness or discomfort; take breaks and seek professional advice for persistent symptoms. Practice recommendations are not medical limits.</p>';
 document.getElementById('ps-prev').onclick=()=>{month.setMonth(month.getMonth()-1);render();};
 document.getElementById('ps-next').onclick=()=>{month.setMonth(month.getMonth()+1);render();};
 root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{root.querySelector('[name=date]').value=b.dataset.date;root.querySelector('[name=date]').scrollIntoView({behavior:'smooth',block:'center'});});
 root.querySelector('#ps-session').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.sessions.push({id:String(Date.now())+Math.random(),date:f.get('date'),instrument:f.get('instrument'),minutes:Number(f.get('minutes')),status:f.get('status'),rating:f.get('rating'),notes:f.get('notes')});save();render();};
 root.querySelector('#ps-goal').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),days=f.getAll('day').map(Number),end=f.get('deadline');if(!days.length){message='Choose at least one weekday.';render();return;}let count=0;const start=new Date(today()+'T12:00:00');const finish=new Date(end+'T12:00:00');for(let d=new Date(start);d<=finish&&count<366;d.setDate(d.getDate()+1)){if(days.includes((d.getDay()+6)%7)){const date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');data.sessions.push({id:String(Date.now())+Math.random(),date,instrument:f.get('instrument'),minutes:Number(f.get('minutes')),status:'planned',rating:'',notes:'Goal: '+f.get('title')});count++;}}data.goals.push({title:f.get('title'),deadline:end,instrument:f.get('instrument'),created:today()});save();message='Created '+count+' planned sessions. You can edit by deleting and re-adding individual sessions.';render();};
 root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const s=data.sessions.find(x=>x.id===b.dataset.toggle);if(s){s.status=s.status==='done'?'planned':'done';save();render();}});
 root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this session?'))return;data.sessions=data.sessions.filter(x=>x.id!==b.dataset.delete);save();render();});
}
render();
