// Practice Studio · offline-first, device-local practice journal.
const root=document.getElementById('practice-studio-content');
const KEY='eriks-music-lab:practice-studio:v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const today=()=>dateKey(new Date());
const localDate=s=>new Date(s+'T12:00:00');
const instruments=['Piano','Singing','Guitar','Bass','Violin','Drums','Wind instrument','Other'];
let data={sessions:[],goals:[],vacations:[]},page='overview',month=new Date(),selected=today(),message='',editing=null,filter='All';
month.setDate(1);
try{const stored=JSON.parse(localStorage.getItem(KEY));if(stored&&Array.isArray(stored.sessions)&&Array.isArray(stored.goals))data={...stored,vacations:Array.isArray(stored.vacations)?stored.vacations:[]};}catch{}
data.sessions.forEach(s=>{if(s.instrument==='Voice / Singing')s.instrument='Singing';});data.goals.forEach(g=>{if(g.instrument==='Voice / Singing')g.instrument='Singing';});
const isVacation=date=>data.vacations.includes(date);
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));message='Saved locally on this device.';return true;}catch{message='Storage is unavailable. Your changes may not persist.';return false;}}
const fmt=n=>Math.floor(n/60)+'h '+String(n%60).padStart(2,'0')+'m';
const total=rows=>rows.reduce((n,s)=>n+(s.status==='done'?Number(s.minutes)||0:0),0);
const options=(values,current)=>values.map(v=>'<option value="'+esc(v)+'" '+(v===current?'selected':'')+'>'+esc(v)+'</option>').join('');
const dayNames=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const stages=[
 {title:'Explore & understand',detail:'Listen, map the piece, identify difficult passages and choose fingerings.'},
 {title:'Build the foundations',detail:'Work slowly on technique and small sections; focus on accuracy.'},
 {title:'Connect & develop',detail:'Join sections, gradually increase tempo and build consistency.'},
 {title:'Refine & express',detail:'Improve phrasing, dynamics and the most difficult transitions.'},
 {title:'Perform & review',detail:'Practice full runs, record a rehearsal and reflect on progress.'}
];
function stageFor(i,count){return Math.min(stages.length-1,Math.floor(i*stages.length/count));}
function goalSessions(id){return data.sessions.filter(s=>s.goalId===id);}
function milestones(g){const sessions=goalSessions(g.id),completed=sessions.filter(s=>s.status==='done').length;return '<div class="ps-milestones">'+stages.map((stage,i)=>{const group=sessions.filter(s=>s.stage===i);const finished=group.filter(s=>s.status==='done').length;return '<div class="ps-milestone"><span class="ps-milestone-number">'+(i+1)+'</span><div><strong>'+esc(stage.title)+'</strong><small>'+esc(stage.detail)+'</small><small>'+finished+'/'+group.length+' sessions completed</small></div></div>';}).join('')+'</div><div class="ps-progress"><span style="width:'+(sessions.length?Math.round(completed/sessions.length*100):0)+'%"></span></div><small>'+completed+'/'+sessions.length+' planned sessions completed</small>';}
function nextAvailableDate(s,goal,occupied){const days=Array.isArray(goal.days)?goal.days:[0,2,4];let d=localDate(today());d.setDate(d.getDate()+1);const end=localDate(goal.deadline);for(;d<=end;d.setDate(d.getDate()+1)){const key=dateKey(d);if(days.includes((d.getDay()+6)%7)&&!occupied.has(key)&&!isVacation(key))return key;}return null;}

function entry(s){return '<article class="ps-entry"><div class="ps-entry-main"><strong>'+esc(s.instrument)+'</strong><small>'+esc(s.date)+' · '+esc(s.minutes)+' min · '+(s.status==='done'?'Completed':'Planned')+(s.rating?' · ★ '+esc(s.rating)+'/5':'')+'</small>'+(s.notes?'<p>'+esc(s.notes)+'</p>':'')+(Number.isInteger(s.stage)&&s.goalId?'<small class="ps-stage-label">Phase '+(s.stage+1)+' · '+esc(stages[s.stage]?.title||'Practice')+'</small>':'')+'</div><div class="ps-entry-actions"><button type="button" data-action="toggle" data-id="'+esc(s.id)+'">'+(s.status==='planned'?'Complete':'Replan')+'</button><button type="button" data-action="edit" data-id="'+esc(s.id)+'">Edit</button><button type="button" data-action="delete" data-id="'+esc(s.id)+'" aria-label="Delete session">×</button></div></article>';}
function list(rows,empty){return rows.length?rows.map(entry).join(''):'<p class="ps-empty">'+empty+'</p>';}
function stats(){const now=today(),monday=localDate(now);monday.setDate(monday.getDate()-(monday.getDay()+6)%7);const done=data.sessions.filter(s=>s.status==='done'&&!isVacation(s.date));return [{name:'This week',value:fmt(total(done.filter(s=>s.date>=dateKey(monday)&&s.date<=now)))},{name:'This month',value:fmt(total(done.filter(s=>s.date.slice(0,7)===now.slice(0,7))))},{name:'All time',value:fmt(total(done))}];}
function calendar(){const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),offset=(first.getDay()+6)%7,now=today();let days='<div class="ps-weekdays">'+dayNames.map(d=>'<span>'+d+'</span>').join('')+'</div><div class="ps-calendar ps-calendar-large">';for(let i=0;i<offset;i++)days+='<span aria-hidden="true"></span>';for(let i=1;i<=last.getDate();i++){const key=dateKey(new Date(month.getFullYear(),month.getMonth(),i)),rows=data.sessions.filter(s=>s.date===key),done=rows.filter(s=>s.status==='done'),planned=rows.filter(s=>s.status==='planned');days+='<button type="button" class="ps-day '+(key===now?'ps-today ':'')+(key===selected?'ps-selected ':'')+(isVacation(key)?'ps-vacation':'')+'" data-date="'+key+'" aria-label="'+key+', '+done.length+' completed, '+planned.length+' planned"><strong>'+i+'</strong><span class="ps-dots">'+(done.length?'<i class="ps-dot-done"></i>':'')+(planned.length?'<i class="ps-dot-plan"></i>':'')+'</span><small>'+(rows.length?fmt(total(done)):'')+'</small></button>';}return '<section class="ps-panel ps-calendar-panel"><div class="ps-heading"><div><span class="ps-kicker">YOUR SCHEDULE</span><h2>Practice Calendar</h2></div><div class="ps-month-nav"><button id="ps-prev" type="button" aria-label="Previous month">‹</button><strong>'+first.toLocaleDateString('en-US',{month:'long',year:'numeric'})+'</strong><button id="ps-next" type="button" aria-label="Next month">›</button></div></div>'+days+'</div><div class="ps-calendar-legend"><span><i class="ps-dot-done"></i> Completed</span><span><i class="ps-dot-plan"></i> Planned</span></div><div class="ps-day-detail"><div><strong>'+localDate(selected).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})+'</strong><small>'+data.sessions.filter(s=>s.date===selected).length+' sessions'+(isVacation(selected)?' · Vacation':'')+'</small></div><div class="ps-day-actions"><button type="button" class="ps-soft-button" data-action="vacation">'+(isVacation(selected)?'Remove vacation':'Mark vacation')+'</button><button type="button" class="ps-soft-button" data-action="add-date">+ Add session</button></div></div>'+list(data.sessions.filter(s=>s.date===selected),'No sessions on this day.')+'</section>';}
function overview(){const now=today(),upcoming=data.sessions.filter(s=>s.status==='planned'&&s.date>=now).sort((a,b)=>a.date.localeCompare(b.date));return '<section class="ps-panel ps-upcoming"><div class="ps-heading"><div><span class="ps-kicker">NEXT UP</span><h2>Upcoming sessions</h2></div><button class="ps-soft-button" data-page="session">+ Plan session</button></div>'+list(upcoming.slice(0,4),'Nothing planned yet. Add your next practice session!')+(upcoming.length>4?'<button class="ps-text-link" data-page="sessions">View all '+upcoming.length+' planned sessions →</button>':'')+'</section>'+calendar()+'<section class="ps-panel ps-time-statistics"><div class="ps-heading"><div><span class="ps-kicker">YOUR PROGRESS</span><h2>Time Statistics</h2></div><button class="ps-text-link" data-page="insights">More insights →</button></div><div class="ps-stats">'+stats().map(x=>'<div><small>'+x.name+'</small><strong>'+x.value+'</strong></div>').join('')+'</div></section>';}

function sessionForm(){const s=data.sessions.find(x=>x.id===editing)||{},status=s.status||'done';return '<section class="ps-panel"><span class="ps-kicker">PRACTICE JOURNAL</span><h2>'+(editing?'Edit session':'Add a practice session')+'</h2><form id="ps-session"><div class="ps-fields"><label>Date<input type="date" name="date" value="'+esc(s.date||selected)+'" required></label><label>Instrument<select name="instrument">'+options(instruments,s.instrument||'Piano')+'</select></label><label>Duration (minutes)<input type="number" name="minutes" min="1" max="1440" value="'+esc(s.minutes||30)+'" required></label><label>Status<select name="status">'+options(['done','planned'],status)+'</select></label><label>Session rating<select name="rating">'+options(['','1','2','3','4','5'],String(s.rating||''))+'</select></label></div><label>What did you practice?<textarea name="notes" rows="4" maxlength="1000" placeholder="Exercises, pieces, observations…">'+esc(s.notes||'')+'</textarea></label><div class="ps-form-actions"><button class="primary" type="submit">'+(editing?'Save changes':'Save session')+'</button><button type="button" class="ps-soft-button" data-page="overview">Cancel</button></div></form></section>';}
function goalForm(){return '<section class="ps-panel"><span class="ps-kicker">LONG-TERM GROWTH</span><h2>Create a practice goal</h2><p class="micro">Choose your available days and a deadline. We will schedule sessions automatically. You can edit each one later.</p><form id="ps-goal"><label>What do you want to learn?<input name="title" required maxlength="100" placeholder="Learn a new piano piece"></label><div class="ps-fields"><label>Instrument<select name="instrument">'+options(instruments,'Piano')+'</select></label><label>Deadline<input name="deadline" type="date" min="'+today()+'" required></label><label>Minutes per session<input name="minutes" type="number" min="5" max="240" value="30" required></label></div><fieldset><legend>Available practice days</legend>'+dayNames.map((d,i)=>'<label class="ps-check"><input name="day" type="checkbox" value="'+i+'" '+([0,2,4].includes(i)?'checked':'')+'>'+d+'</label>').join('')+'</fieldset><button class="primary" type="submit">Generate practice plan</button></form></section><section class="ps-panel"><h2>Your goals</h2>'+(data.goals.length?data.goals.map(g=>'<div class="ps-goal-card"><div class="ps-goal-entry"><div><strong>'+esc(g.title)+'</strong><small>'+esc(g.instrument)+' · Due '+esc(g.deadline)+'</small></div><button type="button" class="ps-soft-button" data-action="delete-goal" data-id="'+esc(g.id||'')+'">Remove plan</button></div>'+milestones(g)+'<div class="ps-goal-actions"><button type="button" class="ps-soft-button" data-action="reschedule" data-id="'+esc(g.id||'')+'">Reschedule missed sessions</button></div></div>').join(''):'<p class="ps-empty">No goals created yet.</p>')+'</section>';}
function history(){const now=today(),upcoming=data.sessions.filter(s=>s.status==='planned'&&s.date>=now),past=data.sessions.filter(s=>s.status==='done'),missed=data.sessions.filter(s=>s.status==='planned'&&s.date<now);const matching=rows=>rows.filter(s=>filter==='All'||s.instrument===filter);return '<section class="ps-panel"><div class="ps-heading"><h2>Session library</h2><button data-page="session" class="ps-soft-button">+ Add</button></div><label>Filter by instrument<select id="ps-filter">'+options(['All',...instruments],filter)+'</select></label><h3>Upcoming sessions</h3>'+list(matching(upcoming).sort((a,b)=>a.date.localeCompare(b.date)),'No upcoming sessions.')+'<h3>Unfinished past plans</h3>'+list(matching(missed).sort((a,b)=>b.date.localeCompare(a.date)),'No overdue plans.')+'<h3>Completed sessions</h3>'+list(matching(past).sort((a,b)=>b.date.localeCompare(a.date)),'No completed sessions.')+'</section>';}
let insightInstrument='All',insightPeriod='30',insightRating='All';
function insights(){
 const now=localDate(today()),end=today(),start=new Date(now);
 if(insightPeriod!=='all')start.setDate(start.getDate()-(Number(insightPeriod)-1));
 const from=insightPeriod==='all'?'0000-01-01':dateKey(start);
 const rows=data.sessions.filter(s=>s.status==='done'&&!isVacation(s.date)&&s.date>=from&&s.date<=end&&(insightInstrument==='All'||s.instrument===insightInstrument)&&(insightRating==='All'||(insightRating==='Unrated'?!s.rating:String(s.rating)===insightRating)));
 const days=[];if(insightPeriod==='all'){const earliest=rows.map(s=>s.date).sort()[0]||end;for(let d=localDate(earliest);d<=now;d.setDate(d.getDate()+1))if(!isVacation(dateKey(d)))days.push(dateKey(d));}else{for(let d=new Date(start);d<=now;d.setDate(d.getDate()+1))if(!isVacation(dateKey(d)))days.push(dateKey(d));}
 const count=days.length,minutes=total(rows),weeks=count/7;
 const rated=rows.filter(s=>Number(s.rating)>0),average=rated.length?(rated.reduce((n,s)=>n+Number(s.rating),0)/rated.length).toFixed(1):'—';
 const by=instruments.map(name=>({name,time:total(rows.filter(s=>s.instrument===name)),count:rows.filter(s=>s.instrument===name).length})).filter(x=>x.count),max=Math.max(1,...by.map(x=>x.time));
 const ratingRows=['1','2','3','4','5','Unrated'].map(r=>({name:r==='Unrated'?'Unrated':r+' / 5',count:rows.filter(s=>r==='Unrated'?!s.rating:String(s.rating)===r).length,time:total(rows.filter(s=>r==='Unrated'?!s.rating:String(s.rating)===r))}));
 const byDay=dayNames.map((name,i)=>({name,count:rows.filter(s=>(localDate(s.date).getDay()+6)%7===i).length,time:total(rows.filter(s=>(localDate(s.date).getDay()+6)%7===i))}));
 return '<section class="ps-panel"><span class="ps-kicker">REFLECT & IMPROVE</span><h2>Practice insights</h2><div class="ps-insight-filters"><label>Instrument<select id="ps-insight-instrument">'+options(['All',...instruments],insightInstrument)+'</select></label><label>Time period<select id="ps-insight-period">'+[['7','Last 7 days'],['30','Last 30 days'],['90','Last 90 days'],['365','Last 365 days'],['all','All time']].map(([v,n])=>'<option value="'+v+'" '+(insightPeriod===v?'selected':'')+'>'+n+'</option>').join('')+'</select></label><label>Rating<select id="ps-insight-rating">'+options(['All','1','2','3','4','5','Unrated'],insightRating)+'</select></label></div><p class="micro">Vacation days are excluded from totals and daily/weekly averages. Filters apply to all figures below.</p><div class="ps-stats ps-insight-stats"><div><small>Sessions</small><strong>'+rows.length+'</strong></div><div><small>Total time</small><strong>'+fmt(minutes)+'</strong></div><div><small>Average rating</small><strong>'+average+'</strong></div><div><small>Avg / available day</small><strong>'+fmt(count?Math.round(minutes/count):0)+'</strong></div><div><small>Avg / week</small><strong>'+fmt(weeks?Math.round(minutes/weeks):0)+'</strong></div><div><small>Avg session</small><strong>'+fmt(rows.length?Math.round(minutes/rows.length):0)+'</strong></div></div><h3>Time by instrument</h3>'+(by.length?by.map(x=>'<div class="ps-insight"><div><strong>'+esc(x.name)+'</strong><span>'+x.count+' sessions · '+fmt(x.time)+'</span></div><div class="ps-bar"><i style="width:'+(x.time/max*100)+'%"></i></div></div>').join(''):'<p class="ps-empty">No completed sessions match these filters.</p>')+'<h3>Rating breakdown</h3><div class="ps-breakdown">'+ratingRows.map(x=>'<div><strong>'+x.name+'</strong><span>'+x.count+' sessions</span><span>'+fmt(x.time)+'</span></div>').join('')+'</div><h3>By weekday</h3><div class="ps-breakdown">'+byDay.map(x=>'<div><strong>'+x.name+'</strong><span>'+x.count+' sessions</span><span>'+fmt(x.time)+'</span></div>').join('')+'</div><p class="micro">'+count+' non-vacation calendar days in the selected period.</p></section><section class="ps-panel"><h2>Practice with care</h2><p>Short, focused sessions and breaks can be more useful than simply adding hours. For singing, respond to fatigue, hoarseness or pain rather than following a fixed hour limit. Seek professional advice if symptoms persist.</p></section>';
}

function render(){root.innerHTML='<div class="ps-shell"><nav class="ps-tabs" aria-label="Practice Studio sections">'+[['overview','Overview'],['session','Add session'],['sessions','Sessions'],['goals','Goals'],['insights','Insights']].map(([id,label])=>'<button type="button" data-page="'+id+'" class="'+(page===id?'active':'')+'" aria-current="'+(page===id?'page':'false')+'">'+label+'</button>').join('')+'</nav>'+(page==='overview'?overview():page==='session'?sessionForm():page==='sessions'?history():page==='goals'?goalForm():insights())+'<p class="ps-save-status" role="status">'+esc(message)+'</p><p class="ps-local-note">Your practice data stays on this device. Clearing browser storage may erase it.</p></div>';bind();}
function bind(){
 root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;if(page==='session')editing=null;render();});
 root.querySelector('[data-action="vacation"]')?.addEventListener('click',()=>{if(isVacation(selected)){data.vacations=data.vacations.filter(d=>d!==selected);}else{data.vacations.push(selected);}save();render();});
 root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;render();});
 root.querySelector('#ps-prev')?.addEventListener('click',()=>{month.setMonth(month.getMonth()-1);selected=dateKey(new Date(month.getFullYear(),month.getMonth(),1));render();});
 root.querySelector('#ps-next')?.addEventListener('click',()=>{month.setMonth(month.getMonth()+1);selected=dateKey(new Date(month.getFullYear(),month.getMonth(),1));render();});
 root.querySelector('[data-action="add-date"]')?.addEventListener('click',()=>{editing=null;page='session';render();});
 for(const [id,set] of [['ps-insight-instrument',v=>insightInstrument=v],['ps-insight-period',v=>insightPeriod=v],['ps-insight-rating',v=>insightRating=v]])root.querySelector('#'+id)?.addEventListener('change',e=>{set(e.target.value);render();});
 root.querySelector('#ps-filter')?.addEventListener('change',e=>{filter=e.target.value;render();});
 root.querySelector('#ps-session')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),date=f.get('date'),minutes=Number(f.get('minutes'));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(minutes)||minutes<1||minutes>1440)return;const previous=data.sessions.find(x=>x.id===editing);const item={...previous,id:editing||String(Date.now())+Math.random(),date,instrument:f.get('instrument'),minutes,status:f.get('status'),rating:f.get('rating'),notes:String(f.get('notes')).slice(0,1000)};if(editing){const i=data.sessions.findIndex(s=>s.id===editing);if(i>=0)data.sessions[i]=item;}else data.sessions.push(item);selected=date;month=localDate(date);month.setDate(1);editing=null;save();page='overview';render();});
 root.querySelector('#ps-goal')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),days=f.getAll('day').map(Number),end=f.get('deadline'),duration=Number(f.get('minutes'));if(!days.length){message='Please select at least one weekday.';render();return;}if(end<today()||duration<5||duration>240)return;const id=String(Date.now())+Math.random(),goal={id,title:String(f.get('title')).slice(0,100),instrument:f.get('instrument'),deadline:end,created:today(),days};let count=0;const dates=[];for(let d=localDate(today()),finish=localDate(end);d<=finish&&dates.length<366;d.setDate(d.getDate()+1)){if(days.includes((d.getDay()+6)%7)&&!isVacation(dateKey(d)))dates.push(dateKey(d));}dates.forEach((date,i)=>{const stage=stageFor(i,dates.length),task=stages[stage];data.sessions.push({id:id+'-'+i,goalId:id,stage,date,instrument:goal.instrument,minutes:duration,status:'planned',rating:'',notes:task.title+': '+task.detail});count++;});data.goals.push(goal);save();message='Scheduled '+count+' practice sessions for '+goal.title+'.';page='overview';render();});
 root.querySelectorAll('[data-action="toggle"]').forEach(b=>b.onclick=()=>{const s=data.sessions.find(x=>x.id===b.dataset.id);if(s){s.status=s.status==='done'?'planned':'done';save();render();}});
 root.querySelectorAll('[data-action="edit"]').forEach(b=>b.onclick=()=>{editing=b.dataset.id;page='session';render();});
 root.querySelectorAll('[data-action="delete"]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this practice session?'))return;data.sessions=data.sessions.filter(s=>s.id!==b.dataset.id);save();render();});
 root.querySelectorAll('[data-action="reschedule"]').forEach(b=>b.onclick=()=>{
 const goal=data.goals.find(g=>g.id===b.dataset.id);if(!goal)return;
 const overdue=goalSessions(goal.id).filter(s=>s.status==='planned'&&s.date<today()).sort((a,b)=>a.date.localeCompare(b.date));
 if(!overdue.length){message='No missed sessions to reschedule.';render();return;}
 const occupied=new Set(goalSessions(goal.id).filter(s=>s.date>=today()).map(s=>s.date));
 let moved=0;
 for(const session of overdue){const date=nextAvailableDate(session,goal,occupied);if(!date)break;session.date=date;occupied.add(date);moved++;}
 save();message=moved+' missed sessions moved to free practice days before the deadline.'+(moved<overdue.length?' '+(overdue.length-moved)+' could not fit; consider extending your deadline or editing sessions.':'');render();
 });
 root.querySelectorAll('[data-action="delete-goal"]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this goal and its unfinished planned sessions?'))return;const id=b.dataset.id;data.goals=data.goals.filter(g=>g.id!==id);data.sessions=data.sessions.filter(s=>s.goalId!==id||s.status==='done');save();render();});
}
render();
