// Recording Studio v1: single-track, local-first, non-destructive editing.
const $=id=>document.getElementById('rs-'+id);
const DB='eriks-music-lab:recordings:v1';
let db,recorder,stream,chunks=[],started=0,tick,recording=false,current=null,player=null,objectURL=null;
const status=$('status'),audio=$('audio'),list=$('library'),name=$('name');
function message(s){status.textContent=s;}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('tracks',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function store(mode,action){db??=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('tracks',mode),req=action(tx.objectStore('tracks'));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function refresh(){try{const tracks=await store('readonly',s=>s.getAll());tracks.sort((a,b)=>b.created-a.created);list.replaceChildren();if(!tracks.length)list.textContent='No recordings yet.';for(const track of tracks){const row=document.createElement('div');row.className='rs-library-row';const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=track.name+' · '+new Date(track.created).toLocaleDateString();button.addEventListener('click',()=>select(track));row.append(button);const del=document.createElement('button');del.type='button';del.className='text-button';del.textContent='Delete';del.addEventListener('click',async()=>{if(!confirm('Delete this recording permanently?'))return;await store('readwrite',s=>s.delete(track.id));if(current?.id===track.id)clearSelection();await refresh();});row.append(del);list.append(row);}}catch(e){message('Local storage unavailable: '+e.message);}}
let audioCtx,sourceNode,dry,wet,convolver,delayNode,feedbackNode,echoWet;
function impulse(ctx){const length=Math.floor(ctx.sampleRate*2.4),buffer=ctx.createBuffer(2,length,ctx.sampleRate);for(let c=0;c<2;c++){const data=buffer.getChannelData(c);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,2.8);}return buffer;}
async function setupEffects(){if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;audioCtx=new AC();sourceNode=audioCtx.createMediaElementSource(audio);dry=audioCtx.createGain();wet=audioCtx.createGain();convolver=audioCtx.createConvolver();convolver.buffer=impulse(audioCtx);delayNode=audioCtx.createDelay(1);feedbackNode=audioCtx.createGain();echoWet=audioCtx.createGain();sourceNode.connect(dry).connect(audioCtx.destination);sourceNode.connect(convolver).connect(wet).connect(audioCtx.destination);sourceNode.connect(delayNode).connect(echoWet).connect(audioCtx.destination);delayNode.connect(feedbackNode).connect(delayNode);updateEffects();}if(audioCtx.state==='suspended')await audioCtx.resume();}
function updateEffects(){const rv=Number($('reverb').value)/100,ev=Number($('echo').value)/100,ms=Number($('delay').value);$('reverb-value').textContent=Math.round(rv*100)+'%';$('echo-value').textContent=Math.round(ev*100)+'%';$('delay-value').textContent=ms+' ms';if(!audioCtx)return;dry.gain.value=1;wet.gain.value=rv*.75;echoWet.gain.value=ev*.7;delayNode.delayTime.value=ms/1000;feedbackNode.gain.value=ev*.55;}
for(const id of ['reverb','echo','delay'])$(id).addEventListener('input',updateEffects);
$('reset-effects').addEventListener('click',()=>{$('reverb').value=0;$('echo').value=0;$('delay').value=300;updateEffects();});
audio.addEventListener('play',()=>setupEffects().catch(e=>message('Audio effects unavailable: '+e.message)));
async function drawWave(blob){const canvas=$('waveform'),g=canvas.getContext('2d'),w=canvas.width,h=canvas.height;g.clearRect(0,0,w,h);g.fillStyle='#f032aa';try{const AC=window.AudioContext||window.webkitAudioContext;const context=new AC();const decoded=await context.decodeAudioData(await blob.arrayBuffer());const samples=decoded.getChannelData(0),step=Math.max(1,Math.floor(samples.length/w));for(let x=0;x<w;x++){let peak=0;for(let k=x*step;k<Math.min((x+1)*step,samples.length);k+=Math.max(1,Math.floor(step/40)))peak=Math.max(peak,Math.abs(samples[k]));const bar=Math.max(2,peak*h*.86);g.fillRect(x,(h-bar)/2,1,bar);}await context.close();}catch(e){g.fillText('Waveform unavailable for this audio format',16,h/2);}}
function clearSelection(){current=null;audio.pause();audio.removeAttribute('src');audio.load();if(objectURL)URL.revokeObjectURL(objectURL);objectURL=null;$('editor').hidden=true;}
function select(track){clearSelection();current=track;name.value=track.name;objectURL=URL.createObjectURL(track.blob);audio.src=objectURL;$('editor').hidden=false;drawWave(track.blob);message('Ready to play or edit. Original recording is preserved.');}
async function save(blob,label){const track={id:crypto.randomUUID(),created:Date.now(),name:label||'Recording',blob};await store('readwrite',s=>s.put(track));select(track);await refresh();}
$('start').addEventListener('click',async()=>{if(recording)return;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Microphone recording is not supported here');stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>message('Recording error.');recorder.onstop=async()=>{clearInterval(tick);stream?.getTracks().forEach(t=>t.stop());stream=null;recording=false;$('start').disabled=false;$('stop').disabled=true;try{await save(new Blob(chunks,{type:recorder.mimeType||'audio/mp4'}),'Recording '+new Date().toLocaleString());message('Recording saved locally.');}catch(e){message('Could not save recording: '+e.message);}};recorder.start(1000);started=Date.now();recording=true;$('start').disabled=true;$('stop').disabled=false;tick=setInterval(()=>{$('time').textContent=Math.floor((Date.now()-started)/1000)+' s';},250);message('Recording… Keep this app open.');}catch(e){stream?.getTracks().forEach(t=>t.stop());message('Cannot start recording: '+e.message);}});
$('stop').addEventListener('click',()=>{if(recording&&recorder?.state==='recording')recorder.stop();});
$('import').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(!file.type.startsWith('audio/'))throw Error('Choose an audio file');await save(file,file.name);message('Audio imported.');}catch(err){message(err.message);}e.target.value='';});
$('rename').addEventListener('click',async()=>{if(!current)return;current.name=name.value.trim()||'Recording';try{await store('readwrite',s=>s.put(current));await refresh();message('Name saved.');}catch(e){message(e.message);}});
function effects(){audio.playbackRate=Number($('speed').value);$('speed-value').textContent=audio.playbackRate.toFixed(2)+'×';}
$('speed').addEventListener('input',effects);
$('download').addEventListener('click',()=>{if(!current)return;const url=URL.createObjectURL(current.blob),a=document.createElement('a');a.href=url;a.download=(current.name.replace(/[^a-z0-9 _-]/gi,'_')||'recording')+(current.blob.type.includes('mp4')?'.m4a':current.blob.type.includes('webm')?'.webm':'.audio');a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);});
document.addEventListener('musiclab:recording-studio-hidden',()=>{audio.pause();if(recording)message('Recording continues. Return to Recording Studio to stop and save.');});
window.addEventListener('pagehide',()=>{if(recording&&recorder?.state==='recording')recorder.stop();});
refresh();
