// Sing the Note: all microphone processing remains on the device.
const root=document.getElementById('sing-note-content');
const NAMES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const note=m=>NAMES[m%12]+(Math.floor(m/12)-1);
const hz=m=>440*Math.pow(2,(m-69)/12);
let mode='single',ref=60,target=65,stream=null,ctx=null,analyser=null,source=null,raf=0,oscillators=[],audio=null,started=0,stable=0,detected=null;
function render(){root.innerHTML='<div class="ps-panel"><h2>Reference type</h2><label>Exercise<select id="sing-mode"><option value="single">Single note</option><option value="chord">Major or minor chord</option><option value="scale">Major scale</option></select></label><p class="micro">The reference is named. Sing the target note shown below.</p><div class="sing-target"><small>REFERENCE</small><h2 id="sing-reference"></h2><button class="primary" id="sing-play" type="button">▶ Play reference</button><small>TARGET NOTE</small><h1 id="sing-target"></h1><p id="sing-readout" role="status">Tap Start microphone, then sing.</p><button class="primary" id="sing-mic" type="button">Start microphone</button><button id="sing-next" type="button">New challenge</button></div><p class="micro">Use headphones to prevent the reference sound from entering the microphone. Microphone audio is processed locally and is never recorded or uploaded. Pitch tracking works best with a steady solo voice in a quiet room.</p></div>';root.querySelector('#sing-mode').value=mode;root.querySelector('#sing-mode').onchange=e=>{mode=e.target.value;newChallenge();};root.querySelector('#sing-play').onclick=play;root.querySelector('#sing-mic').onclick=()=>stream?stop():start();root.querySelector('#sing-next').onclick=newChallenge;newChallenge();}
function newChallenge(){stop();ref=57+Math.floor(Math.random()*13);target=ref+[-7,-5,-4,-3,-2,0,2,3,4,5,7][Math.floor(Math.random()*11)];target=Math.max(48,Math.min(81,target));root.querySelector('#sing-reference').textContent=mode==='single'?note(ref):mode==='chord'?note(ref)+' '+(ref%2?'minor':'major'):' '+note(ref)+' major scale';root.querySelector('#sing-target').textContent=note(target);root.querySelector('#sing-readout').textContent='Listen, then sing '+note(target)+'.';}
function play(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();audio.resume();oscillators.forEach(o=>{try{o.stop();}catch{}});oscillators=[];const offsets=mode==='single'?[0]:mode==='chord'?(ref%2?[0,3,7]:[0,4,7]):[0,2,4,5,7,9,11,12];offsets.forEach((n,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*(mode==='scale'?.24:0);o.type='sine';o.frequency.value=hz(ref+n);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12/Math.sqrt(offsets.length),t+.025);g.gain.setValueAtTime(.12/Math.sqrt(offsets.length),t+.32);g.gain.linearRampToValueAtTime(0,t+.55);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.57);oscillators.push(o);});}
function pitch(samples,rate){const n=samples.length;let energy=0;for(const v of samples)energy+=v*v;if(Math.sqrt(energy/n)<.012)return null;const min=Math.floor(rate/900),max=Math.min(Math.floor(rate/90),Math.floor(n/2));let best=0,score=0;for(let lag=min;lag<=max;lag++){let sum=0,a=0,b=0;for(let i=0;i<n-max;i+=2){const x=samples[i],y=samples[i+lag];sum+=x*y;a+=x*x;b+=y*y;}const correlation=sum/Math.sqrt(a*b||1);if(correlation>score){score=correlation;best=lag;}}return score>.72&&best?rate/best:null;}
async function start(){if(!navigator.mediaDevices?.getUserMedia){root.querySelector('#sing-readout').textContent='Microphone requires HTTPS and browser permission.';return;}try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});ctx=new (window.AudioContext||window.webkitAudioContext)();source=ctx.createMediaStreamSource(stream);analyser=ctx.createAnalyser();analyser.fftSize=4096;source.connect(analyser);root.querySelector('#sing-mic').textContent='Stop microphone';stable=0;started=performance.now();tick();}catch(e){root.querySelector('#sing-readout').textContent='Microphone unavailable: '+e.message;stop(false);}}
function tick(){if(!analyser)return;const buf=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(buf);const f=pitch(buf,ctx.sampleRate),el=root.querySelector('#sing-readout');if(f){const midi=69+12*Math.log2(f/440),cents=Math.round((midi-target)*100),nearest=Math.round(midi);if(Math.abs(cents)<=35)stable++;else stable=0;el.textContent=stable>=12?'✓ Target held! '+note(target)+' ('+(cents>=0?'+':'')+cents+' cents)':'Detected '+note(nearest)+' · '+(cents>=0?'+':'')+cents+' cents from target '+note(target); }else{stable=0;el.textContent='Listening… sing a steady note.';}raf=requestAnimationFrame(tick);}
function stop(update=true){cancelAnimationFrame(raf);raf=0;analyser=null;source?.disconnect();source=null;stream?.getTracks().forEach(t=>t.stop());stream=null;ctx?.close();ctx=null;if(update&&root.querySelector('#sing-mic'))root.querySelector('#sing-mic').textContent='Start microphone';}
document.addEventListener('musiclab:sing-note-hidden',()=>{stop();oscillators.forEach(o=>{try{o.stop();}catch{}});oscillators=[];});
render();
