// Erik's Synth 2.0 — sample-free polyphonic Web Audio instrument.
const STORE='eriks-music-lab:synth:v1';
const base={on1:true,on2:true,wave1:'sawtooth',wave2:'triangle',mix:50,coarse:0,detune:7,sub:0,filtertype:'lowpass',cutoff:2200,resonance:2,filterenv:0,attack:.2,decay:.4,sustain:.7,release:.7,lfo:0,lforate:5,modsource:'off',moddest:'filter',modamount:0,drive:0,delay:0,delaytime:.28,feedback:30,reverb:0};
const presets={
acid:{wave1:'sawtooth',wave2:'square',cutoff:720,resonance:11,filterenv:65,attack:.005,decay:.24,sustain:.3,release:.12,drive:40},
supersaw:{wave1:'sawtooth',wave2:'sawtooth',detune:25,cutoff:8500,attack:.06,release:.55,delay:22},
organ:{wave1:'sine',wave2:'square',mix:22,sub:28,cutoff:7800,attack:.01,decay:.1,sustain:.95,release:.15},
bell:{wave1:'sine',wave2:'triangle',coarse:12,mix:35,attack:.005,decay:1.4,sustain:0,release:1.8,reverb:34},
ambient:{wave1:'triangle',wave2:'sawtooth',detune:18,cutoff:1600,attack:1.4,decay:1.3,sustain:.75,release:2.7,reverb:48,delay:18},
brass:{wave1:'sawtooth',wave2:'square',mix:40,cutoff:2700,filterenv:35,attack:.07,decay:.32,sustain:.68,release:.25},
subbass:{on1:true,on2:false,wave1:'sine',sub:42,cutoff:800,attack:.005,decay:.2,sustain:.85,release:.15},
laser:{wave1:'square',wave2:'sine',coarse:12,cutoff:9000,attack:.005,decay:.08,sustain:0,release:.18,modsource:'env',moddest:'pitch',modamount:95},
chip:{wave1:'square',wave2:'square',coarse:12,cutoff:6000,attack:.005,decay:.1,sustain:.8,release:.06},
choir:{wave1:'triangle',wave2:'sine',detune:13,cutoff:1900,attack:.8,decay:.6,sustain:.7,release:1.8,reverb:32},
pluck2:{wave1:'square',wave2:'triangle',cutoff:5200,attack:.005,decay:.18,sustain:0,release:.15,delay:22},
wobble:{wave1:'sawtooth',wave2:'square',sub:45,cutoff:650,resonance:7,modsource:'lfo',moddest:'filter',modamount:80,lforate:3,attack:.005,release:.18},
warm:{wave1:'sawtooth',wave2:'triangle',attack:.25,decay:.5,sustain:.72,release:1.1},
lead:{wave1:'sawtooth',wave2:'square',detune:9,cutoff:4500,resonance:3,attack:.01,decay:.16,sustain:.75,release:.2,lfo:2},
bass:{wave1:'square',wave2:'sawtooth',detune:-5,cutoff:650,resonance:4,attack:.01,decay:.3,sustain:.45,release:.17},
pluck:{wave1:'triangle',wave2:'sine',detune:0,cutoff:3600,resonance:1,attack:.005,decay:.28,sustain:0,release:.22},
keys:{wave1:'sine',wave2:'triangle',detune:4,cutoff:6000,resonance:.6,attack:.008,decay:.5,sustain:.3,release:.55},
strings:{wave1:'sawtooth',wave2:'sawtooth',detune:13,cutoff:3000,resonance:1,attack:.6,decay:.4,sustain:.85,release:1.5,lfo:5},
'808':{on1:true,on2:false,wave1:'sine',wave2:'triangle',mix:0,sub:0,cutoff:10000,resonance:.5,attack:.005,decay:.3,sustain:.85,release:.24,drive:68,filterenv:0,lfo:0,modsource:'off',bass808:true}
};
const fields=['on1','on2','wave1','wave2','mix','coarse','detune','sub','filtertype','cutoff','resonance','filterenv','attack','decay','sustain','release','lfo','lforate','modsource','moddest','modamount','drive','delay','delaytime','feedback','reverb'];
let userPresets={};try{userPresets=JSON.parse(localStorage.getItem('eriks-music-lab:synth-user-presets:v1')||'{}')||{};}catch{}
const selects=new Set(['wave1','wave2','filtertype','modsource','moddest']);
const stage=document.getElementById('synth-stage'),preset=document.getElementById('synth-preset'),keyboard=document.getElementById('synth-keyboard'),status=document.getElementById('synth-status');
let p={...base},lastFrequency=null,ctx=null,output=null,analyser=null,delayNode=null,feedbackNode=null,delayWet=null,reverbWet=null,driveNode=null,dry=null,voices=new Map(),held=new Set(),order=[],pointers=new Map(),generation=0,drawId=0,starting=null;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function save(){try{localStorage.setItem(STORE,JSON.stringify({preset:preset.value,params:p,octave:document.getElementById('synth-octave').value}));}catch{}}
function setPreset(name){const settings=presets[name]||userPresets[name];if(!settings)return;p={...base,...settings};preset.value=name;render();save();updateEffects();}
function renderUserOptions(){const group=document.getElementById('synth-user-options');group.replaceChildren();for(const name of Object.keys(userPresets).sort()){const o=document.createElement('option');o.value=name;o.textContent=name;group.append(o);}}
renderUserOptions();
function syncMacros(){const values={bright:Math.round(Math.sqrt(Math.max(0,Number(p.cutoff)-120)/11880)*100),punch:Math.round(Math.max(0,Math.min(100,Number(p.drive)/.75))),space:Math.round(Math.max(0,Math.min(100,Number(p.reverb)/.7))),move:p.modsource==='lfo'&&p.moddest==='filter'?Number(p.modamount):0};for(const [name,value] of Object.entries(values)){const el=document.getElementById('synth-macro-'+name);if(el)el.value=String(Math.max(0,Math.min(100,value)));}}
function render(){for(const id of fields){const el=document.getElementById('synth-'+id);if(!el)continue;if(id==='on1'||id==='on2')el.checked=!!p[id];else el.value=String(p[id]);const o=document.getElementById('synth-'+id+'-value');if(o)o.textContent=String(p[id])+(id==='cutoff'?' Hz':id==='detune'?' cents':id==='coarse'?' semitones':id==='lforate'?' Hz':'');}syncMacros();drawEnvelope();}
try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved){if(saved.preset&&(presets[saved.preset]||userPresets[saved.preset]))p={...base,...(presets[saved.preset]||userPresets[saved.preset])};if(saved.params)p={...p,...saved.params};if(saved.preset)preset.value=saved.preset;if(['1','2','3','4','5'].includes(saved.octave))document.getElementById('synth-octave').value=saved.octave;}}catch{}
preset.addEventListener('change',()=>{if(preset.value!=='custom')setPreset(preset.value);});
for(const id of fields){const el=document.getElementById('synth-'+id);el.addEventListener(el.type==='checkbox'?'change':'input',()=>{if(id==='on1'||id==='on2'){if(!el.checked&&!p[id==='on1'?'on2':'on1']){el.checked=true;return;}p[id]=el.checked;}else p[id]=selects.has(id)?el.value:Number(el.value);preset.value='custom';render();updateEffects();save();});}
document.querySelectorAll('[data-synth-section]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-synth-section]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));document.querySelectorAll('.synth-section').forEach(x=>x.hidden=x.id!=='synth-section-'+b.dataset.synthSection);}));
function distortion(amount){const curve=new Float32Array(2048),k=amount/100*140;for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=(1+k)*x/(1+k*Math.abs(x));}return curve;}
function impulse(context){const length=Math.round(context.sampleRate*1.5),buffer=context.createBuffer(2,length,context.sampleRate);for(let ch=0;ch<2;ch++){const data=buffer.getChannelData(ch);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,2.8);}return buffer;}
function updateEffects(){if(!ctx)return;driveNode.curve=distortion(Number(p.drive));delayNode.delayTime.setTargetAtTime(Number(p.delaytime),ctx.currentTime,.02);feedbackNode.gain.setTargetAtTime(Number(p.feedback)/100,ctx.currentTime,.02);delayWet.gain.setTargetAtTime(Number(p.delay)/100*.32,ctx.currentTime,.02);reverbWet.gain.setTargetAtTime(Number(p.reverb)/100*.4,ctx.currentTime,.02);}
async function audio(){if(!ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Web Audio is not supported');ctx=new AC({latencyHint:'interactive'});output=ctx.createGain();output.gain.value=.22;analyser=ctx.createAnalyser();analyser.fftSize=2048;output.connect(analyser).connect(ctx.destination);driveNode=ctx.createWaveShaper();driveNode.oversample='2x';dry=ctx.createGain();dry.gain.value=1;driveNode.connect(dry).connect(output);delayNode=ctx.createDelay(1);feedbackNode=ctx.createGain();delayWet=ctx.createGain();driveNode.connect(delayNode);delayNode.connect(feedbackNode).connect(delayNode);delayNode.connect(delayWet).connect(output);const convolver=ctx.createConvolver();convolver.buffer=impulse(ctx);reverbWet=ctx.createGain();driveNode.connect(convolver).connect(reverbWet).connect(output);updateEffects();}if(ctx.state==='suspended')await ctx.resume();}
function frequency(midi){return 440*Math.pow(2,(midi-69)/12);}
function release(note){const v=voices.get(note);if(!v||!ctx)return;voices.delete(note);order=order.filter(x=>x!==note);const t=ctx.currentTime,rel=Math.max(.02,Number(v.release));v.gain.gain.cancelScheduledValues(t);v.gain.gain.setTargetAtTime(0,t,rel/4);for(const osc of v.osc)try{osc.stop(t+rel+.15);}catch{}for(const lfo of v.lfos)try{lfo.stop(t+rel+.15);}catch{}updateCount();}
function updateCount(){document.getElementById('synth-voice-count').textContent=voices.size+' VOICES';}
async function press(note){held.add(note);if(voices.has(note))return;const token=generation;try{await audio();if(token!==generation||stage.hidden||!held.has(note))return;if(document.getElementById('synth-mono').checked){for(const previous of [...voices.keys()])release(previous);}else if(voices.size>=8)release(order[0]);const t=ctx.currentTime,settings={...p},f=frequency(note),is808=preset.value==='808',amp=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type=settings.filtertype;filter.frequency.value=Number(settings.cutoff);filter.Q.value=Number(settings.resonance);filter.connect(amp).connect(driveNode);
const a=Math.max(.005,Number(settings.attack)),d=Math.max(.02,Number(settings.decay)),sus=clamp(Number(settings.sustain),0,1);
amp.gain.setValueAtTime(0,t);amp.gain.linearRampToValueAtTime(.7,t+a);amp.gain.setTargetAtTime(Math.max(.0001,.7*sus),t+a,d/3);
const osc=[],lfos=[];function addOsc(type,level,detune,sub=false){if(level<=0)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=sub?f/2:f;o.detune.value=detune;g.gain.value=level;o.connect(g).connect(filter);o.start(t);osc.push(o);return o;}
const mix=Number(settings.mix)/100;const glideOn=document.getElementById('synth-mono').checked,glideTime=Number(document.getElementById('synth-glide').value),glideFrom=lastFrequency;lastFrequency=f;
const o1=settings.on1?addOsc(settings.wave1,settings.on2?1-mix:1,0):null;const o2=settings.on2?addOsc(settings.wave2,settings.on1?mix:1,Number(settings.detune)+Number(settings.coarse)*100):null;
addOsc('sine',Number(settings.sub)/100*.5,0,true);if(glideOn&&glideFrom&&glideTime>0){for(const o of osc){const target=o.frequency.value;o.frequency.setValueAtTime(glideFrom*(target/f),t);o.frequency.exponentialRampToValueAtTime(target,t+glideTime);}}
if(is808){for(const o of [o1,o2].filter(Boolean)){o.frequency.setValueAtTime(f*2.8,t);o.frequency.exponentialRampToValueAtTime(f,t+.085);}const transient=ctx.createOscillator(),g=ctx.createGain();transient.type='triangle';transient.frequency.setValueAtTime(160,t);transient.frequency.exponentialRampToValueAtTime(55,t+.04);g.gain.setValueAtTime(.32,t);g.gain.exponentialRampToValueAtTime(.001,t+.045);transient.connect(g).connect(filter);transient.start(t);transient.stop(t+.05);}
if(Number(settings.lfo)>0||settings.modsource==='lfo'&&Number(settings.modamount)>0){const l=ctx.createOscillator(),depth=ctx.createGain();l.frequency.value=Number(settings.lforate)||5;l.connect(depth);if(settings.modsource==='lfo'&&Number(settings.modamount)>0){const amt=Number(settings.modamount);if(settings.moddest==='pitch'){depth.gain.value=amt;for(const o of osc)depth.connect(o.detune);}else if(settings.moddest==='filter'){depth.gain.value=Number(settings.cutoff)*amt/200;depth.connect(filter.frequency);}else{depth.gain.value=amt/100*.22;depth.connect(amp.gain);}}else{depth.gain.value=Number(settings.lfo);for(const o of osc)depth.connect(o.detune);}l.start(t);lfos.push(l);}
if(settings.modsource==='env'&&Number(settings.modamount)>0){const amount=Number(settings.modamount)/100;if(settings.moddest==='filter'){const baseHz=Number(settings.cutoff);filter.frequency.setValueAtTime(baseHz,t);filter.frequency.linearRampToValueAtTime(Math.min(18000,baseHz*(1+amount*5)),t+a);filter.frequency.setTargetAtTime(baseHz,t+a,d/3);}else if(settings.moddest==='pitch'){for(const o of osc){o.detune.setValueAtTime(o.detune.value+amount*500,t);o.detune.linearRampToValueAtTime(o.detune.value-amount*500,t+a+d);}}else{amp.gain.setValueAtTime(0,t);amp.gain.linearRampToValueAtTime(.7*(1+amount),t+a);amp.gain.setTargetAtTime(.7*sus,t+a,d/3);}}
if(Number(settings.filterenv)!==0){const startHz=Number(settings.cutoff),peak=clamp(startHz*Math.pow(2,Number(settings.filterenv)/30),40,18000);filter.frequency.setValueAtTime(startHz,t);filter.frequency.linearRampToValueAtTime(peak,t+a);filter.frequency.setTargetAtTime(startHz,t+a,d/3);}
voices.set(note,{gain:amp,osc,lfos,release:settings.release});order.push(note);updateCount();status.textContent='Playing · '+Math.round(f)+' Hz';keyboard.querySelectorAll('[data-midi="'+note+'"]').forEach(k=>k.classList.add('pressed'));startVisual();}catch(e){status.textContent=e.message;}}
function lift(note){held.delete(note);release(note);keyboard.querySelectorAll('[data-midi="'+note+'"]').forEach(k=>k.classList.remove('pressed'));}
function allOff(){generation++;held.clear();lastFrequency=null;for(const note of [...voices.keys()])lift(note);pointers.clear();keyboard.querySelectorAll('.pressed').forEach(k=>k.classList.remove('pressed'));}
function buildKeyboard(){allOff();keyboard.replaceChildren();const oct=Number(document.getElementById('synth-octave').value),baseMidi=12*(oct+1),black=new Set([1,3,6,8,10]);let white=0;for(let n=0;n<24;n++){const semi=n%12,midi=baseMidi+n,isBlack=black.has(semi),key=document.createElement('button');key.type='button';key.dataset.midi=String(midi);key.className='synth-key '+(isBlack?'black':'white');key.style.left=(isBlack?white*48-15:white*48)+'px';if(!isBlack){white++;if(semi===0)key.textContent='C'+(oct+Math.floor(n/12));}key.setAttribute('aria-label','Play MIDI note '+midi);keyboard.append(key);}}
keyboard.addEventListener('pointerdown',e=>{const key=e.target.closest('.synth-key');if(!key)return;e.preventDefault();const note=Number(key.dataset.midi);pointers.set(e.pointerId,note);try{key.setPointerCapture(e.pointerId);}catch{}press(note);});
function pointerEnd(e){if(!pointers.has(e.pointerId))return;const note=pointers.get(e.pointerId);pointers.delete(e.pointerId);lift(note);}
for(const type of ['pointerup','pointercancel','lostpointercapture'])keyboard.addEventListener(type,pointerEnd);
document.getElementById('synth-octave').addEventListener('change',()=>{buildKeyboard();save();});
document.getElementById('synth-panic').addEventListener('click',allOff);
document.getElementById('synth-glide').addEventListener('input',e=>document.getElementById('synth-glide-value').textContent=Number(e.target.value).toFixed(2)+' s');
document.getElementById('synth-save').addEventListener('click',()=>{const name=prompt('Name your sound (up to 40 characters):');if(!name)return;const safe=name.trim().slice(0,40);if(!safe)return;if(presets[safe]){alert('This name is reserved for a factory preset.');return;}userPresets[safe]={...p};try{localStorage.setItem('eriks-music-lab:synth-user-presets:v1',JSON.stringify(userPresets));}catch{alert('Could not save sound.');return;}renderUserOptions();preset.value=safe;save();});
document.getElementById('synth-export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({format:'eriks-synth-preset-v1',name:preset.value,params:p},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='eriks-synth-sound.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.getElementById('synth-import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>30000)throw Error('File too large');const data=JSON.parse(await file.text());if(data.format!=='eriks-synth-preset-v1'||!data.params||typeof data.params!=='object')throw Error('Invalid preset file');const name=String(data.name||'Imported Sound').slice(0,40);p={...base,...Object.fromEntries(Object.entries(data.params).filter(([k,v])=>fields.includes(k)&&(typeof v==='number'&&Number.isFinite(v)||typeof v==='boolean'||typeof v==='string')))};userPresets[name]={...p};localStorage.setItem('eriks-music-lab:synth-user-presets:v1',JSON.stringify(userPresets));renderUserOptions();preset.value=name;render();save();}catch(err){alert('Could not import sound: '+err.message);}e.target.value='';});
const macroMap={bright:v=>{p.cutoff=Math.round(120+Math.pow(v/100,2)*11880);},punch:v=>{p.attack=Math.max(.005,.5*(1-v/100));p.drive=Math.round(v*.75);},space:v=>{p.reverb=Math.round(v*.7);p.delay=Math.round(v*.35);},move:v=>{p.modsource='lfo';p.moddest='filter';p.modamount=v;p.lforate=1+v/20;}};
for(const [id,fn] of Object.entries(macroMap))document.getElementById('synth-macro-'+id).addEventListener('input',e=>{fn(Number(e.target.value));preset.value='custom';render();updateEffects();save();});
const play=document.getElementById('synth-play'),design=document.getElementById('synth-design'),tabPlay=document.getElementById('synth-tab-play'),tabDesign=document.getElementById('synth-tab-design');
function view(isPlay){play.hidden=!isPlay;design.hidden=isPlay;tabPlay.setAttribute('aria-selected',String(isPlay));tabDesign.setAttribute('aria-selected',String(!isPlay));allOff();}
tabPlay.addEventListener('click',()=>view(true));tabDesign.addEventListener('click',()=>view(false));
const graph=document.getElementById('synth-adsr-graph'),line=document.getElementById('synth-adsr-line'),fill=document.getElementById('synth-adsr-fill'),handles=document.getElementById('synth-adsr-handles');
let points=[];
function drawEnvelope(){if(!graph)return;const a=12+Number(p.attack)/2*105,d=a+Number(p.decay)/2*75,s=d+52,r=s+Number(p.release)/3*70,y=145-Number(p.sustain)*115;points=[[12,145],[a,30],[d,y],[s,y],[r,145]];const path='M'+points.map(pt=>pt.join(' ')).join(' L');line.setAttribute('d',path);fill.setAttribute('d',path+' L12 145 Z');handles.replaceChildren();for(let i=1;i<=4;i++){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',points[i][0]);circle.setAttribute('cy',points[i][1]);circle.setAttribute('r','8');circle.setAttribute('class','synth-adsr-handle');circle.dataset.handle=String(i);handles.append(circle);}}
let dragging=null;
graph.addEventListener('pointerdown',e=>{const target=e.target.closest('[data-handle]');if(!target)return;dragging=Number(target.dataset.handle);graph.setPointerCapture(e.pointerId);e.preventDefault();});
graph.addEventListener('pointermove',e=>{if(dragging===null)return;const rect=graph.getBoundingClientRect(),x=clamp((e.clientX-rect.left)/rect.width*340,12,328),y=clamp((e.clientY-rect.top)/rect.height*170,30,145);if(dragging===1)p.attack=clamp((x-12)/105*2,.005,2);if(dragging===2)p.decay=clamp((x-points[1][0])/75*2,.02,2);if(dragging===3)p.sustain=clamp((145-y)/115,0,1);if(dragging===4)p.release=clamp((x-points[3][0])/70*3,.02,3);preset.value='custom';render();save();});
for(const type of ['pointerup','pointercancel','lostpointercapture'])graph.addEventListener(type,()=>dragging=null);
const canvas=document.getElementById('synth-scope'),g=canvas.getContext('2d'),samples=new Uint8Array(2048);
function visual(){drawId=0;if(stage.hidden)return;const w=canvas.width,h=canvas.height;g.clearRect(0,0,w,h);g.strokeStyle='#1e3e68';g.lineWidth=1;for(let i=1;i<5;i++){g.beginPath();g.moveTo(0,i*h/5);g.lineTo(w,i*h/5);g.stroke();}g.beginPath();g.lineWidth=3;g.strokeStyle='#6eb7ff';g.shadowBlur=12;g.shadowColor='#338dff';if(analyser&&ctx&&ctx.state==='running'){analyser.getByteTimeDomainData(samples);for(let i=0;i<samples.length;i++){const x=i/(samples.length-1)*w,y=samples[i]/255*h;i?g.lineTo(x,y):g.moveTo(x,y);}}else{for(let i=0;i<w;i+=3){const y=h/2+Math.sin(i*.024)*3;i?g.lineTo(i,y):g.moveTo(i,y);}}g.stroke();g.shadowBlur=0;if(voices.size)drawId=requestAnimationFrame(visual);}
function startVisual(){if(!drawId)drawId=requestAnimationFrame(visual);}
document.addEventListener('musiclab:synth-hidden',()=>{allOff();if(drawId)cancelAnimationFrame(drawId);drawId=0;if(ctx){const old=ctx;ctx=null;output=null;analyser=null;old.close().catch(()=>{});}status.textContent='Tap a key to start audio.';visual();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)allOff();});
window.addEventListener('pagehide',allOff);
render();buildKeyboard();visual();
